//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_NDam.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI_NDam.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animace.
        /// </summary>
        internal static string Animace {
            get {
                return ResourceManager.GetString("Animace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkový počet řešení.
        /// </summary>
        internal static string Celkový {
            get {
                return ResourceManager.GetString("Celkový", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Další řešení.
        /// </summary>
        internal static string Další {
            get {
                return ResourceManager.GetString("Další", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Dáma {
            get {
                object obj = ResourceManager.GetObject("Dáma", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hra.
        /// </summary>
        internal static string Hra {
            get {
                return ResourceManager.GetString("Hra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec.
        /// </summary>
        internal static string Konec {
            get {
                return ResourceManager.GetString("Konec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nápověda.
        /// </summary>
        internal static string Nápověda {
            get {
                return ResourceManager.GetString("Nápověda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová úloha.
        /// </summary>
        internal static string Nová {
            get {
                return ResourceManager.GetString("Nová", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úloha N dam.
        /// </summary>
        internal static string OProgramuText1 {
            get {
                return ResourceManager.GetString("OProgramuText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © OndraPavlovič 2023.
        /// </summary>
        internal static string OProgramuText2 {
            get {
                return ResourceManager.GetString("OProgramuText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programu.
        /// </summary>
        internal static string OProgramuTitulek {
            get {
                return ResourceManager.GetString("OProgramuTitulek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přerušit animaci.
        /// </summary>
        internal static string Přerušit {
            get {
                return ResourceManager.GetString("Přerušit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spustit animaci.
        /// </summary>
        internal static string Spustit {
            get {
                return ResourceManager.GetString("Spustit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problém {0} dam, je zobrazeno {1}. řešení.
        /// </summary>
        internal static string TitulekOkna {
            get {
                return ResourceManager.GetString("TitulekOkna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit řešení do souboru.
        /// </summary>
        internal static string Ulož {
            get {
                return ResourceManager.GetString("Ulož", resourceCulture);
            }
        }
    }
}
